/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDAO;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.List;

/**
 *
 * @author raiii
 */
public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        configurarTabela();
        corrigirScroll();
        
        jPanel1.setBackground(new java.awt.Color(173, 216, 230)); // Azul claro
        
        setTitle("Listagem de Cursos");
        setSize(800, 400);
        setLocationRelativeTo(null); // centraliza
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        bntAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        scrollTabela = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setText("Pesquise aqui...");
        jPanel1.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, -1));

        bntPesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\raiii\\OneDrive\\Documentos\\NetBeansProjects\\prg03projetoindividualraika\\src\\main\\java\\br\\com\\ifba\\image\\lupa (1).png")); // NOI18N
        jPanel1.add(bntPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 30, 30));

        bntAdicionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\raiii\\OneDrive\\Documentos\\NetBeansProjects\\prg03projetoindividualraika\\src\\main\\java\\br\\com\\ifba\\image\\adicao (1).png")); // NOI18N
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(bntAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 30));

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCursos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 47, 470, 258));
        jPanel1.add(scrollTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 20, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        CursoSalvar tela = new CursoSalvar();
        tela.setVisible(true);
    }//GEN-LAST:event_bntAdicionarActionPerformed
    private void configurarTabela() {
        // 1) Cria o modelo com as colunas e dados de exemplo
    String[] colunas = {"Código", "Nome", "Carga Horária", "Ativo", "Editar", "Remover"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(colunas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column >= 4; // só as duas últimas colunas são editáveis
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 3) return Boolean.class; // coluna "Ativo"
            return String.class;
        }
    };
    
    CursoDAO dao = new CursoDAO();
    List<Curso> lista = dao.buscarTodos();
    
     for (Curso c : lista) {
            modelo.addRow(new Object[]{
                c.getCodigoCurso(),
                c.getNome(), 
                c.getCargaHoraria(),
                c.isAtivo(),
                "Editar",
                "Remover",
            });
     }

    // 2) Atribui o modelo à tabela
    tblCursos.setModel(modelo);

    // 3) Impede redimensionamento automático — faça isso antes de definir larguras
    tblCursos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

    // 4) Ajusta largura das colunas (agora que o modelo está definido)
    tblCursos.getColumnModel().getColumn(0).setPreferredWidth(60);  // Código
    tblCursos.getColumnModel().getColumn(1).setPreferredWidth(220); // Nome
    tblCursos.getColumnModel().getColumn(2).setPreferredWidth(100); // Carga Horária
    tblCursos.getColumnModel().getColumn(3).setPreferredWidth(60);  // Ativo
    tblCursos.getColumnModel().getColumn(4).setPreferredWidth(70);  // Editar
    tblCursos.getColumnModel().getColumn(5).setPreferredWidth(80);  // Remover

    // 5) Aparência
    tblCursos.setRowHeight(30);
    tblCursos.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    tblCursos.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    }

    private void corrigirScroll() {
    // Remove o scroll vazio, se ainda existir
    if (scrollTabela != null) {
        jPanel1.remove(scrollTabela);
    }

    // Garante que a tabela está dentro do scroll principal
    jScrollPane1.setViewportView(tblCursos);

    // Ajusta tamanho e política de rolagem
    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    // Redimensiona a área do scroll corretamente
    jScrollPane1.setBounds(20, 50, 600, 250);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {}

        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
