/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.dao.CursoDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author raiii
 */
public class CursoSalvar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoSalvar.class.getName());

    /**
     * Creates new form CursoSalvar
     */
    public CursoSalvar() {
        initComponents();
        
        setTitle("Salvar Curso");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome do Curso: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 43, -1, -1));

        jLabel2.setText("Código do Curso: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 83, -1, -1));

        txtNome.setText("Digite aqui");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 40, 97, -1));

        txtCodigo.setText("Digite aqui");
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 80, 97, -1));

        bntSalvar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel3.setText("Carga Horária: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtCargaHoraria.setText("Digite aqui");
        getContentPane().add(txtCargaHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        try{
            String nome = txtNome.getText().trim();//esse trim serve para ver se o usuário não digitou só espaço 
            String codigo = txtCodigo.getText().trim();
            String cargaHoraria = txtCargaHoraria.getText().trim();
            
            if(nome.isEmpty() || codigo.isEmpty() || cargaHoraria.isEmpty()){//verifica se os campos estáo vazios
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!", 
                        "Entrada inválida", JOptionPane.WARNING_MESSAGE);
                return;//sai sem salvar
            }
            
            if(!nome.matches("[\\p{L} ]+")){//bloqueia números, mas aceita acentos e espaços
                JOptionPane.showMessageDialog(this, "O nome do curso deve conter apenas letras!", 
                    "Entrada inválida", JOptionPane.WARNING_MESSAGE);
                return;//sai sem salvar
            }
            
            Curso curso = new Curso(nome, codigo, cargaHoraria);
        
            CursoDAO c = new CursoDAO();
            c.save(curso);
            
            JOptionPane.showMessageDialog(null, "Curso salvo com sucesso!!",
                    "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERRO ao salvar curso" + e.getMessage(),
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bntSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoSalvar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
